# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import apex_datatype_pb2 as apex__datatype__pb2


class BufferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTrajectories = channel.stream_unary(
                '/Buffer/SendTrajectories',
                request_serializer=apex__datatype__pb2.ListNDarray.SerializeToString,
                response_deserializer=apex__datatype__pb2.Nothing.FromString,
                )
        self.SendExperiences = channel.stream_unary(
                '/Buffer/SendExperiences',
                request_serializer=apex__datatype__pb2.ListNDarray.SerializeToString,
                response_deserializer=apex__datatype__pb2.Nothing.FromString,
                )


class BufferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTrajectories(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendExperiences(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BufferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTrajectories': grpc.stream_unary_rpc_method_handler(
                    servicer.SendTrajectories,
                    request_deserializer=apex__datatype__pb2.ListNDarray.FromString,
                    response_serializer=apex__datatype__pb2.Nothing.SerializeToString,
            ),
            'SendExperiences': grpc.stream_unary_rpc_method_handler(
                    servicer.SendExperiences,
                    request_deserializer=apex__datatype__pb2.ListNDarray.FromString,
                    response_serializer=apex__datatype__pb2.Nothing.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Buffer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Buffer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTrajectories(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Buffer/SendTrajectories',
            apex__datatype__pb2.ListNDarray.SerializeToString,
            apex__datatype__pb2.Nothing.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendExperiences(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Buffer/SendExperiences',
            apex__datatype__pb2.ListNDarray.SerializeToString,
            apex__datatype__pb2.Nothing.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
