# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apex_datatype.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='apex_datatype.proto',
  package='apex_datatype',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x61pex_datatype.proto\x12\rapex_datatype\"\t\n\x07Nothing\"\x17\n\x07NDarray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1b\n\x0bListNDarray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x0c\"+\n\x0c\x45xpsAndPrios\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x0c\x12\r\n\x05prios\x18\x02 \x01(\x0c\x62\x06proto3'
)




_NOTHING = _descriptor.Descriptor(
  name='Nothing',
  full_name='apex_datatype.Nothing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=47,
)


_NDARRAY = _descriptor.Descriptor(
  name='NDarray',
  full_name='apex_datatype.NDarray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='apex_datatype.NDarray.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=72,
)


_LISTNDARRAY = _descriptor.Descriptor(
  name='ListNDarray',
  full_name='apex_datatype.ListNDarray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='apex_datatype.ListNDarray.data', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=101,
)


_EXPSANDPRIOS = _descriptor.Descriptor(
  name='ExpsAndPrios',
  full_name='apex_datatype.ExpsAndPrios',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='apex_datatype.ExpsAndPrios.data', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prios', full_name='apex_datatype.ExpsAndPrios.prios', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['Nothing'] = _NOTHING
DESCRIPTOR.message_types_by_name['NDarray'] = _NDARRAY
DESCRIPTOR.message_types_by_name['ListNDarray'] = _LISTNDARRAY
DESCRIPTOR.message_types_by_name['ExpsAndPrios'] = _EXPSANDPRIOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), {
  'DESCRIPTOR' : _NOTHING,
  '__module__' : 'apex_datatype_pb2'
  # @@protoc_insertion_point(class_scope:apex_datatype.Nothing)
  })
_sym_db.RegisterMessage(Nothing)

NDarray = _reflection.GeneratedProtocolMessageType('NDarray', (_message.Message,), {
  'DESCRIPTOR' : _NDARRAY,
  '__module__' : 'apex_datatype_pb2'
  # @@protoc_insertion_point(class_scope:apex_datatype.NDarray)
  })
_sym_db.RegisterMessage(NDarray)

ListNDarray = _reflection.GeneratedProtocolMessageType('ListNDarray', (_message.Message,), {
  'DESCRIPTOR' : _LISTNDARRAY,
  '__module__' : 'apex_datatype_pb2'
  # @@protoc_insertion_point(class_scope:apex_datatype.ListNDarray)
  })
_sym_db.RegisterMessage(ListNDarray)

ExpsAndPrios = _reflection.GeneratedProtocolMessageType('ExpsAndPrios', (_message.Message,), {
  'DESCRIPTOR' : _EXPSANDPRIOS,
  '__module__' : 'apex_datatype_pb2'
  # @@protoc_insertion_point(class_scope:apex_datatype.ExpsAndPrios)
  })
_sym_db.RegisterMessage(ExpsAndPrios)


# @@protoc_insertion_point(module_scope)
