# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apex_learner.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import apex_datatype_pb2 as apex__datatype__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='apex_learner.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x61pex_learner.proto\x1a\x13\x61pex_datatype.proto2\xb6\x02\n\x07Learner\x12\x42\n\x0eSendNumpyArray\x12\x16.apex_datatype.NDarray\x1a\x16.apex_datatype.Nothing\"\x00\x12K\n\x13SendBatchNumpyArray\x12\x1a.apex_datatype.ListNDarray\x1a\x16.apex_datatype.Nothing\"\x00\x12\x41\n\tGetParams\x12\x16.apex_datatype.Nothing\x1a\x1a.apex_datatype.ListNDarray\"\x00\x12W\n\x1bSendExperienceGetPriorities\x12\x1a.apex_datatype.ListNDarray\x1a\x1a.apex_datatype.ListNDarray\"\x00\x62\x06proto3'
  ,
  dependencies=[apex__datatype__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_LEARNER = _descriptor.ServiceDescriptor(
  name='Learner',
  full_name='Learner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=44,
  serialized_end=354,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendNumpyArray',
    full_name='Learner.SendNumpyArray',
    index=0,
    containing_service=None,
    input_type=apex__datatype__pb2._NDARRAY,
    output_type=apex__datatype__pb2._NOTHING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendBatchNumpyArray',
    full_name='Learner.SendBatchNumpyArray',
    index=1,
    containing_service=None,
    input_type=apex__datatype__pb2._LISTNDARRAY,
    output_type=apex__datatype__pb2._NOTHING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetParams',
    full_name='Learner.GetParams',
    index=2,
    containing_service=None,
    input_type=apex__datatype__pb2._NOTHING,
    output_type=apex__datatype__pb2._LISTNDARRAY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendExperienceGetPriorities',
    full_name='Learner.SendExperienceGetPriorities',
    index=3,
    containing_service=None,
    input_type=apex__datatype__pb2._LISTNDARRAY,
    output_type=apex__datatype__pb2._LISTNDARRAY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LEARNER)

DESCRIPTOR.services_by_name['Learner'] = _LEARNER

# @@protoc_insertion_point(module_scope)
