# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import apex_datatype_pb2 as apex__datatype__pb2


class LearnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNumpyArray = channel.unary_unary(
                '/Learner/SendNumpyArray',
                request_serializer=apex__datatype__pb2.NDarray.SerializeToString,
                response_deserializer=apex__datatype__pb2.Nothing.FromString,
                )
        self.SendBatchNumpyArray = channel.unary_unary(
                '/Learner/SendBatchNumpyArray',
                request_serializer=apex__datatype__pb2.ListNDarray.SerializeToString,
                response_deserializer=apex__datatype__pb2.Nothing.FromString,
                )
        self.GetParams = channel.unary_unary(
                '/Learner/GetParams',
                request_serializer=apex__datatype__pb2.Nothing.SerializeToString,
                response_deserializer=apex__datatype__pb2.ListNDarray.FromString,
                )
        self.SendExperienceGetPriorities = channel.unary_unary(
                '/Learner/SendExperienceGetPriorities',
                request_serializer=apex__datatype__pb2.ListNDarray.SerializeToString,
                response_deserializer=apex__datatype__pb2.ListNDarray.FromString,
                )


class LearnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendNumpyArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendBatchNumpyArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendExperienceGetPriorities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNumpyArray': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNumpyArray,
                    request_deserializer=apex__datatype__pb2.NDarray.FromString,
                    response_serializer=apex__datatype__pb2.Nothing.SerializeToString,
            ),
            'SendBatchNumpyArray': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBatchNumpyArray,
                    request_deserializer=apex__datatype__pb2.ListNDarray.FromString,
                    response_serializer=apex__datatype__pb2.Nothing.SerializeToString,
            ),
            'GetParams': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParams,
                    request_deserializer=apex__datatype__pb2.Nothing.FromString,
                    response_serializer=apex__datatype__pb2.ListNDarray.SerializeToString,
            ),
            'SendExperienceGetPriorities': grpc.unary_unary_rpc_method_handler(
                    servicer.SendExperienceGetPriorities,
                    request_deserializer=apex__datatype__pb2.ListNDarray.FromString,
                    response_serializer=apex__datatype__pb2.ListNDarray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Learner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Learner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendNumpyArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Learner/SendNumpyArray',
            apex__datatype__pb2.NDarray.SerializeToString,
            apex__datatype__pb2.Nothing.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendBatchNumpyArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Learner/SendBatchNumpyArray',
            apex__datatype__pb2.ListNDarray.SerializeToString,
            apex__datatype__pb2.Nothing.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Learner/GetParams',
            apex__datatype__pb2.Nothing.SerializeToString,
            apex__datatype__pb2.ListNDarray.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendExperienceGetPriorities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Learner/SendExperienceGetPriorities',
            apex__datatype__pb2.ListNDarray.SerializeToString,
            apex__datatype__pb2.ListNDarray.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
