# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apex_buffer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import apex_datatype_pb2 as apex__datatype__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='apex_buffer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x61pex_buffer.proto\x1a\x13\x61pex_datatype.proto2\xa2\x01\n\x06\x42uffer\x12J\n\x10SendTrajectories\x12\x1a.apex_datatype.ListNDarray\x1a\x16.apex_datatype.Nothing\"\x00(\x01\x12L\n\x0fSendExperiences\x12\x1d.apex_datatype.ExpsAndTDerror\x1a\x16.apex_datatype.Nothing\"\x00(\x01\x62\x06proto3'
  ,
  dependencies=[apex__datatype__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BUFFER = _descriptor.ServiceDescriptor(
  name='Buffer',
  full_name='Buffer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=43,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendTrajectories',
    full_name='Buffer.SendTrajectories',
    index=0,
    containing_service=None,
    input_type=apex__datatype__pb2._LISTNDARRAY,
    output_type=apex__datatype__pb2._NOTHING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendExperiences',
    full_name='Buffer.SendExperiences',
    index=1,
    containing_service=None,
    input_type=apex__datatype__pb2._EXPSANDTDERROR,
    output_type=apex__datatype__pb2._NOTHING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUFFER)

DESCRIPTOR.services_by_name['Buffer'] = _BUFFER

# @@protoc_insertion_point(module_scope)
