from .dqn import DQN
from .ddqn import DDQN
from .duelingdqn import DDDQN
from .dpg import DPG
from .ddpg import DDPG
from .td3 import TD3
from .sac import SAC
from .sac_no_v import SAC_NO_V
from .pg import PG
from .ppo import PPO
from .ac import AC
from .a2c import A2C
from .maxsqn import MAXSQN
from .ma_dpg import MADPG
from .ma_ddpg import MADDPG
from .ma_td3 import MATD3