env_name: sisl.multiwalker_v7

env_config:
  n_walkers: 3
  position_noise: 1.e-3
  angle_noise: 1.e-3
  local_ratio: 1.0
  forward_reward: 1.0
  terminate_reward: -100.0
  fall_reward: -10.0
  terminate_on_fall: True
  remove_on_fall: True
  max_cycles: 500
