super_config: 'sarl_off_policy'

polyak: 0.995
use_target_action_noise: false
noise_action: "clip_normal"
noise_params:
  sigma: 0.2
actor_lr: 5.0e-4
critic_lr: 1.0e-3
discrete_tau: 1.0
network_settings:
  actor_continuous: [ 64, 64 ]
  actor_discrete: [ 64, 64 ]
  q: [ 64, 64 ]