super_config: 'sarl_off_policy'

q_lr: 5.0e-3
intra_option_lr: 5.0e-4
termination_lr: 5.0e-4
interest_lr: 5.0e-4
ent_coff: 0.01
boltzmann_temperature: 1.0
use_baseline: true
terminal_mask: true
double_q: false
termination_regularizer: 0.01
options_num: 4
assign_interval: 1000
network_settings:
  q: [ 32, 32 ]
  intra_option: [ 32, 32 ]
  termination: [ 32, 32 ]
  interest: [ 32, 32 ]