super_config: 'sarl_off_policy'
q_lr: 5.0e-3
intra_option_lr: 5.0e-4
termination_lr: 5.0e-4
use_eps_greedy: false
eps_init: 1
eps_mid: 0.2
eps_final: 0.01
ent_coff: 0.01
boltzmann_temperature: 1.0
use_baseline: true
terminal_mask: true
double_q: false
termination_regularizer: 0.01
init2mid_annealing_step: 10000
options_num: 4
assign_interval: 1000
network_settings:
  q: [ 32, 32 ]
  intra_option: [ 32, 32 ]
  termination: [ 32, 32 ]