super_config: 'marl_off_policy'

#mixer: "vdn"
#mixer_settings: { }
lr: 5.0e-4
eps_init: 1
eps_mid: 0.2
eps_final: 0.01
use_double: true
init2mid_annealing_step: 10000
assign_interval: 1000
network_settings:
share: [ 64 ]
v: [ 64 ]
adv: [ 64 ]


mixer: "qatten"
mixer_settings:
  agent_own_state_size: 1 # TODO: implement this
  query_hidden_units: [ 64 ]
  query_embed_dim: 32
  key_embed_dim: 32
  head_hidden_units: [ 64 ]
  n_attention_head: 4
  constrant_hidden_units: [ 32 ]
  is_weighted: true